# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/vivado/DDFS/DDFS.cache/wt [current_project]
set_property parent.project_path C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/vivado/DDFS/DDFS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/vivado/DDFS/DDFS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/src/dff.vhd
  C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/src/fa.vhd
  C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/src/reg.vhd
  C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/src/rca.vhd
  C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/src/LUT_DDFS_SG_4096x6.vhd
  C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/src/PhaseAccumulator.vhd
  C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/src/DDFS.vhd
  C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/src/DDFS_wrapper.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/vivado/DDFS/DDFS.srcs/constrs_1/new/DDFS_Zybo_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/fu/Dropbox/UNI/MASTER/1M/PSM/DIGITALE/2018_vhdl/2-DDFS/vivado/DDFS/DDFS.srcs/constrs_1/new/DDFS_Zybo_constraints.xdc]


synth_design -top DDFS_WRAPPER -part xc7z010clg400-1


write_checkpoint -force -noxdef DDFS_WRAPPER.dcp

catch { report_utilization -file DDFS_WRAPPER_utilization_synth.rpt -pb DDFS_WRAPPER_utilization_synth.pb }
