//////////////////////////////////////////////
// Project Name:     DDFS verilog
//                   
// Group:            
// Author(s):        Francesco Urbani
// 
// Create Date:      Fri Jan 18 14:25:20 CEST 2019
// Design Name: 
// Module Name:      lut_ddfs
// Target Devices:   Intel MAX10 10M50DAF484C7G
// Tool versions: 
// Description:      
//
// THIS FILE IS AUTOGENERATED BY LUT_generator.py
// WARNING! All changes made in this file might be lost!
//
// Revision:
//////////////////////////////////////////////


module lut_ddfs
#(
    parameter      N = 8,
    parameter      M = 4
)
(
    input wire   [N-1:0]     lut_line,
    output reg   [M-1:0]     lut_data
);
    

always @ (*) 
begin
    case (lut_line)

		0 : lut_data = 7;
		1 : lut_data = 7;
		2 : lut_data = 7;
		3 : lut_data = 7;
		4 : lut_data = 7;
		5 : lut_data = 7;
		6 : lut_data = 8;
		7 : lut_data = 8;
		8 : lut_data = 8;
		9 : lut_data = 8;
		10 : lut_data = 8;
		11 : lut_data = 8;
		12 : lut_data = 9;
		13 : lut_data = 9;
		14 : lut_data = 9;
		15 : lut_data = 9;
		16 : lut_data = 9;
		17 : lut_data = 9;
		18 : lut_data = 9;
		19 : lut_data = 10;
		20 : lut_data = 10;
		21 : lut_data = 10;
		22 : lut_data = 10;
		23 : lut_data = 10;
		24 : lut_data = 10;
		25 : lut_data = 11;
		26 : lut_data = 11;
		27 : lut_data = 11;
		28 : lut_data = 11;
		29 : lut_data = 11;
		30 : lut_data = 11;
		31 : lut_data = 11;
		32 : lut_data = 11;
		33 : lut_data = 12;
		34 : lut_data = 12;
		35 : lut_data = 12;
		36 : lut_data = 12;
		37 : lut_data = 12;
		38 : lut_data = 12;
		39 : lut_data = 12;
		40 : lut_data = 12;
		41 : lut_data = 12;
		42 : lut_data = 13;
		43 : lut_data = 13;
		44 : lut_data = 13;
		45 : lut_data = 13;
		46 : lut_data = 13;
		47 : lut_data = 13;
		48 : lut_data = 13;
		49 : lut_data = 13;
		50 : lut_data = 13;
		51 : lut_data = 13;
		52 : lut_data = 13;
		53 : lut_data = 13;
		54 : lut_data = 13;
		55 : lut_data = 13;
		56 : lut_data = 13;
		57 : lut_data = 13;
		58 : lut_data = 13;
		59 : lut_data = 13;
		60 : lut_data = 13;
		61 : lut_data = 13;
		62 : lut_data = 13;
		63 : lut_data = 13;
		64 : lut_data = 14;
		65 : lut_data = 13;
		66 : lut_data = 13;
		67 : lut_data = 13;
		68 : lut_data = 13;
		69 : lut_data = 13;
		70 : lut_data = 13;
		71 : lut_data = 13;
		72 : lut_data = 13;
		73 : lut_data = 13;
		74 : lut_data = 13;
		75 : lut_data = 13;
		76 : lut_data = 13;
		77 : lut_data = 13;
		78 : lut_data = 13;
		79 : lut_data = 13;
		80 : lut_data = 13;
		81 : lut_data = 13;
		82 : lut_data = 13;
		83 : lut_data = 13;
		84 : lut_data = 13;
		85 : lut_data = 13;
		86 : lut_data = 13;
		87 : lut_data = 12;
		88 : lut_data = 12;
		89 : lut_data = 12;
		90 : lut_data = 12;
		91 : lut_data = 12;
		92 : lut_data = 12;
		93 : lut_data = 12;
		94 : lut_data = 12;
		95 : lut_data = 12;
		96 : lut_data = 11;
		97 : lut_data = 11;
		98 : lut_data = 11;
		99 : lut_data = 11;
		100 : lut_data = 11;
		101 : lut_data = 11;
		102 : lut_data = 11;
		103 : lut_data = 11;
		104 : lut_data = 10;
		105 : lut_data = 10;
		106 : lut_data = 10;
		107 : lut_data = 10;
		108 : lut_data = 10;
		109 : lut_data = 10;
		110 : lut_data = 9;
		111 : lut_data = 9;
		112 : lut_data = 9;
		113 : lut_data = 9;
		114 : lut_data = 9;
		115 : lut_data = 9;
		116 : lut_data = 9;
		117 : lut_data = 8;
		118 : lut_data = 8;
		119 : lut_data = 8;
		120 : lut_data = 8;
		121 : lut_data = 8;
		122 : lut_data = 8;
		123 : lut_data = 7;
		124 : lut_data = 7;
		125 : lut_data = 7;
		126 : lut_data = 7;
		127 : lut_data = 7;
		128 : lut_data = 7;
		129 : lut_data = 6;
		130 : lut_data = 6;
		131 : lut_data = 6;
		132 : lut_data = 6;
		133 : lut_data = 6;
		134 : lut_data = 5;
		135 : lut_data = 5;
		136 : lut_data = 5;
		137 : lut_data = 5;
		138 : lut_data = 5;
		139 : lut_data = 5;
		140 : lut_data = 4;
		141 : lut_data = 4;
		142 : lut_data = 4;
		143 : lut_data = 4;
		144 : lut_data = 4;
		145 : lut_data = 4;
		146 : lut_data = 4;
		147 : lut_data = 3;
		148 : lut_data = 3;
		149 : lut_data = 3;
		150 : lut_data = 3;
		151 : lut_data = 3;
		152 : lut_data = 3;
		153 : lut_data = 2;
		154 : lut_data = 2;
		155 : lut_data = 2;
		156 : lut_data = 2;
		157 : lut_data = 2;
		158 : lut_data = 2;
		159 : lut_data = 2;
		160 : lut_data = 2;
		161 : lut_data = 1;
		162 : lut_data = 1;
		163 : lut_data = 1;
		164 : lut_data = 1;
		165 : lut_data = 1;
		166 : lut_data = 1;
		167 : lut_data = 1;
		168 : lut_data = 1;
		169 : lut_data = 1;
		170 : lut_data = 0;
		171 : lut_data = 0;
		172 : lut_data = 0;
		173 : lut_data = 0;
		174 : lut_data = 0;
		175 : lut_data = 0;
		176 : lut_data = 0;
		177 : lut_data = 0;
		178 : lut_data = 0;
		179 : lut_data = 0;
		180 : lut_data = 0;
		181 : lut_data = 0;
		182 : lut_data = 0;
		183 : lut_data = 0;
		184 : lut_data = 0;
		185 : lut_data = 0;
		186 : lut_data = 0;
		187 : lut_data = 0;
		188 : lut_data = 0;
		189 : lut_data = 0;
		190 : lut_data = 0;
		191 : lut_data = 0;
		192 : lut_data = 0;
		193 : lut_data = 0;
		194 : lut_data = 0;
		195 : lut_data = 0;
		196 : lut_data = 0;
		197 : lut_data = 0;
		198 : lut_data = 0;
		199 : lut_data = 0;
		200 : lut_data = 0;
		201 : lut_data = 0;
		202 : lut_data = 0;
		203 : lut_data = 0;
		204 : lut_data = 0;
		205 : lut_data = 0;
		206 : lut_data = 0;
		207 : lut_data = 0;
		208 : lut_data = 0;
		209 : lut_data = 0;
		210 : lut_data = 0;
		211 : lut_data = 0;
		212 : lut_data = 0;
		213 : lut_data = 0;
		214 : lut_data = 0;
		215 : lut_data = 1;
		216 : lut_data = 1;
		217 : lut_data = 1;
		218 : lut_data = 1;
		219 : lut_data = 1;
		220 : lut_data = 1;
		221 : lut_data = 1;
		222 : lut_data = 1;
		223 : lut_data = 1;
		224 : lut_data = 2;
		225 : lut_data = 2;
		226 : lut_data = 2;
		227 : lut_data = 2;
		228 : lut_data = 2;
		229 : lut_data = 2;
		230 : lut_data = 2;
		231 : lut_data = 2;
		232 : lut_data = 3;
		233 : lut_data = 3;
		234 : lut_data = 3;
		235 : lut_data = 3;
		236 : lut_data = 3;
		237 : lut_data = 3;
		238 : lut_data = 4;
		239 : lut_data = 4;
		240 : lut_data = 4;
		241 : lut_data = 4;
		242 : lut_data = 4;
		243 : lut_data = 4;
		244 : lut_data = 4;
		245 : lut_data = 5;
		246 : lut_data = 5;
		247 : lut_data = 5;
		248 : lut_data = 5;
		249 : lut_data = 5;
		250 : lut_data = 5;
		251 : lut_data = 6;
		252 : lut_data = 6;
		253 : lut_data = 6;
		254 : lut_data = 6;
		255 : lut_data = 6;

     endcase

end
endmodule
    